import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docs: [
		"index",
		{
			type: "category",
			label: "Getting Started",
			collapsed: false,
			items: [
				"getting-started/install",
				"getting-started/quickstart-docker",
				"getting-started/quickstart-managed",
			],
		},
		{
			type: "category",
			label: "Concepts",
			items: [
				"concepts/time-machine",
				"concepts/shadow-db",
				"concepts/ai-review",
			],
		},
		{
			type: "category",
			label: "Reference",
			items: ["reference/components", "reference/cli"],
		},
		{
			type: "category",
			label: "Guides",
			items: ["guides/migrating-from-infra-x-postgres-library"],
		},
		{
			type: "category",
			label: "Examples",
			items: ["examples"],
		},
		{
			type: "category",
			label: "About",
			items: ["about/why-db-x", "about/north-star", "about/roadmap"],
		},
		{
			type: "category",
			label: "API Reference",
			link: { type: "doc", id: "api/index" },
			items: [
				{
					type: "autogenerated",
					dirName: "api",
				},
			],
		},
		{
			type: "category",
			label: "Releases",
			items: ["changelog"],
		},
	],
};

export default sidebars;
